# Generated by Django 5.1.6 on 2025-04-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.course', verbose_name='课程名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselesson',
            name='is_show_list',
            field=models.BooleanField(default=False, verbose_name='是否在课程列表中显示'),
        ),
    ]
