# Generated by Django 5.1.6 on 2025-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courselesson_course_courselesson_is_show_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='lesson',
            field=models.IntegerField(default=1, verbose_name='第几课时'),
            preserve_default=False,
        ),
    ]
