# Generated by Django 5.1.6 on 2025-05-14 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_activity_coursediscounttype_coursediscount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="如果这里填写的价格为0，则表明当前课程不能购买永久有效的期限",
                max_digits=6,
                verbose_name="课程原价",
            ),
        ),
        migrations.CreateModel(
            name="CourseExpire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("order", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "expire_time",
                    models.IntegerField(
                        blank=True,
                        help_text="有效期按天数计算",
                        null=True,
                        verbose_name="有效期",
                    ),
                ),
                (
                    "expire_text",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="提示文本"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="课程价格",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_expire",
                        to="course.course",
                        verbose_name="课程名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程有效期",
                "verbose_name_plural": "课程有效期",
                "db_table": "ly_course_expire",
            },
        ),
    ]
