# Generated by Django 5.1.6 on 2025-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_desc",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="订单描述"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pay_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="pay_type",
            field=models.SmallIntegerField(
                choices=[(0, "支付宝"), (1, "微信支付")],
                default=1,
                verbose_name="支付方式",
            ),
        ),
    ]
