# Generated by Django 5.1.6 on 2025-07-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_order_desc_alter_order_pay_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon",
            field=models.IntegerField(null=True, verbose_name="拥有优惠券的用户ID"),
        ),
    ]
