# Generated by Django 5.1.6 on 2025-03-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信号'),
        ),
    ]
