# Generated by Django 5.1.6 on 2025-07-17 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_login", "0002_user_wechat"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit",
            field=models.IntegerField(blank=True, default=0, verbose_name="用户积分"),
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("order", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "opera",
                    models.SmallIntegerField(
                        choices=[(1, "赚取"), (2, "消费")], verbose_name="操作类型"
                    ),
                ),
                (
                    "number",
                    models.SmallIntegerField(default=0, verbose_name="积分数值"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_credit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分流水",
                "verbose_name_plural": "积分流水",
                "db_table": "ly_credit",
            },
        ),
    ]
