# Generated by Django 5.1.6 on 2025-07-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_course_price_courseexpire"),
        ("user_login", "0003_user_credit_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="opera",
            field=models.SmallIntegerField(
                choices=[(0, "赚取"), (1, "消费")], verbose_name="操作类型"
            ),
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("order", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "trade_no",
                    models.CharField(
                        blank=True,
                        help_text="将来依靠流水号到支付平台查账单",
                        max_length=128,
                        null=True,
                        verbose_name="支付平台的流水号",
                    ),
                ),
                (
                    "buy_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "用户购买"),
                            (2, "免费活动"),
                            (3, "活动赠品"),
                            (4, "系统赠送"),
                        ],
                        default=1,
                        verbose_name="购买方式",
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="购买时间"
                    ),
                ),
                (
                    "out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="course_users",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程购买记录",
                "verbose_name_plural": "课程购买记录",
                "db_table": "ly_user_course",
            },
        ),
    ]
